export const site = {
  name: "Ronit",
  legalName: "Ronit Pet Kennel",
  brandName: "Ronit",
  alternateNames: ["Ronit", "Ronit Pet Kennel", "Ronit Pet Kennel Lucknow"],
  description:
    "Buy healthy, vet-checked puppies in Lucknow with transparent pricing, verified records, and local support.",
  city: "Lucknow",
  region: "Uttar Pradesh",
  country: "IN",
  serviceAreas: [
    "Cantonment",
    "Arjunganj",
    "Gomti Nagar",
    "Indira Nagar",
    "Aliganj",
    "Hazratganj",
    "Lucknow Cantt",
  ],
  address: {
    locality: "Cantonment",
    city: "Lucknow",
    region: "Uttar Pradesh",
    postalCode: "226002",
    country: "IN",
  },
  geo: {
    latitude: 26.7606,
    longitude: 80.9959,
  },
  url: "https://www.pawluxe.com",
  email: "contact@pawluxe.com",
  phone: "+91 70546 11731",
  phoneHref: "+917054611731",
  ratingValue: 4.4,
  reviewCount: 85,
  locale: "en_US",
} as const;
